const surveyQuestions = [
    { question: "Do you enjoy solving complex problems and puzzles?", program: "Science, Technology, and Engineering (SPSTE)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about new technologies and innovations?", program: "Science, Technology, and Engineering (SPSTE)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy working with your hands and building things?", program: "Special Program for Technical-Vocational Education (SPTVE)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning foreign languages and cultures?", program: "Special Program in Foreign Language (SPFL)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy writing and storytelling?", program: "Special Program in Journalism (SPJ)", weight: Math.random().toFixed(2) },
    { question: "Are you passionate about sports and physical activities?", program: "Special Program in Sports (SPS)", weight: Math.random().toFixed(2) },
    { question: "Do you have an interest in visual arts, music, dance, or theater?", program: "Special Program in the Arts (SPA)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy conducting scientific experiments and research?", program: "Science, Technology, and Engineering (SPSTE)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in technical and vocational skills such as automotive technology or electronics?", program: "Special Program for Technical-Vocational Education (SPTVE)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy participating in debates and public speaking?", program: "Special Program in Journalism (SPJ)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about computer programming and software development?", program: "Science, Technology, and Engineering (SPSTE)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy working on group projects and collaborating with others?", program: "Special Program for Technical-Vocational Education (SPTVE)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about different cultures and global issues?", program: "Special Program in Foreign Language (SPFL)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy creating art, whether it be drawing, painting, or sculpting?", program: "Special Program in the Arts (SPA)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about journalism and media production?", program: "Special Program in Journalism (SPJ)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy participating in sports competitions and events?", program: "Special Program in Sports (SPS)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about engineering and how things work?", program: "Science, Technology, and Engineering (SPSTE)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy performing on stage, whether it be acting, singing, or dancing?", program: "Special Program in the Arts (SPA)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about health and fitness?", program: "Special Program in Sports (SPS)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy writing articles, essays, or stories?", program: "Special Program in Journalism (SPJ)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about robotics and automation?", program: "Science, Technology, and Engineering (SPSTE)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy working with numbers and solving mathematical problems?", program: "Science, Technology, and Engineering (SPSTE)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about different languages and linguistics?", program: "Special Program in Foreign Language (SPFL)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy creating digital art and graphic design?", program: "Special Program in the Arts (SPA)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about film and video production?", program: "Special Program in Journalism (SPJ)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy participating in physical fitness activities and exercises?", program: "Special Program in Sports (SPS)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about environmental science and sustainability?", program: "Science, Technology, and Engineering (SPSTE)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy performing arts such as theater, music, or dance?", program: "Special Program in the Arts (SPA)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about nutrition and healthy eating?", program: "Special Program in Sports (SPS)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy writing and editing content for publications?", program: "Special Program in Journalism (SPJ)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about space and astronomy?", program: "Science, Technology, and Engineering (SPSTE)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy working on technical projects and using tools?", program: "Special Program for Technical-Vocational Education (SPTVE)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about cultural anthropology and history?", program: "Special Program in Foreign Language (SPFL)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy creating and editing videos?", program: "Special Program in Journalism (SPJ)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about broadcast journalism and media?", program: "Special Program in Journalism (SPJ)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy participating in team sports and activities?", program: "Special Program in Sports (SPS)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about physics and how the universe works?", program: "Science, Technology, and Engineering (SPSTE)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy creating music or playing musical instruments?", program: "Special Program in the Arts (SPA)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about sports science and athletic training?", program: "Special Program in Sports (SPS)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy writing scripts and screenplays?", program: "Special Program in the Arts (SPA)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about chemistry and chemical reactions?", program: "Science, Technology, and Engineering (SPSTE)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy working on DIY projects and crafts?", program: "Special Program for Technical-Vocational Education (SPTVE)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about international relations and diplomacy?", program: "Special Program in Foreign Language (SPFL)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy creating animations and visual effects?", program: "Special Program in the Arts (SPA)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about public relations and communication?", program: "Special Program in Journalism (SPJ)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy participating in fitness challenges and competitions?", program: "Special Program in Sports (SPS)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about biology and life sciences?", program: "Science, Technology, and Engineering (SPSTE)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy performing in front of an audience?", program: "Special Program in the Arts (SPA)", weight: Math.random().toFixed(2) },
    { question: "Are you interested in learning about sports management and coaching?", program: "Special Program in Sports (SPS)", weight: Math.random().toFixed(2) },
    { question: "Do you enjoy writing reviews and critiques?", program: "Special Program in Journalism (SPJ)", weight: Math.random().toFixed(2) }
];
